namespace WatermarkRemover.App.Services;

public sealed record BottomTextWatermarkDetectorOptions(
    string PresetName,
    int MinExpandX,
    double ExpandWidthScale,
    int MinExpandY,
    double ExpandHeightScale,
    bool IncludeBrightTextUnion,
    int InitialCloseKernelWidth,
    int InitialCloseKernelHeight,
    int DilateKernelWidth,
    int DilateKernelHeight,
    int AdaptiveHorizontalCloseDivisor,
    int AdaptiveHorizontalCloseMaxWidth,
    double FallbackConfidenceCap,
    double BrightThreshold,
    double LowSaturationThreshold,
    double TopHatThreshold,
    double StrokeThreshold,
    double CandidateIntensityThreshold,
    double MinComponentFillRatio,
    double MaxComponentFillRatio,
    double MinimumSolidBlockFillRatio,
    double LargeSolidBlockWidthRatio,
    double LargeSolidBlockHeightRatio,
    double LongEdgeAspectRatio,
    double LongEdgeFillRatio)
{
    public static BottomTextWatermarkDetectorOptions Balanced { get; } = new(
        PresetName: "Balanced",
        MinExpandX: 18,
        ExpandWidthScale: 0.10,
        MinExpandY: 8,
        ExpandHeightScale: 0.45,
        IncludeBrightTextUnion: false,
        InitialCloseKernelWidth: 5,
        InitialCloseKernelHeight: 3,
        DilateKernelWidth: 5,
        DilateKernelHeight: 3,
        AdaptiveHorizontalCloseDivisor: 0,
        AdaptiveHorizontalCloseMaxWidth: 0,
        FallbackConfidenceCap: 0.30,
        BrightThreshold: 146,
        LowSaturationThreshold: 112,
        TopHatThreshold: 11,
        StrokeThreshold: 20,
        CandidateIntensityThreshold: 156,
        MinComponentFillRatio: 0.08,
        MaxComponentFillRatio: 0.90,
        MinimumSolidBlockFillRatio: 0.68,
        LargeSolidBlockWidthRatio: 0.38,
        LargeSolidBlockHeightRatio: 0.54,
        LongEdgeAspectRatio: 7.5,
        LongEdgeFillRatio: 0.50);

    public static BottomTextWatermarkDetectorOptions CoverageBoost { get; } = new(
        PresetName: "CoverageBoost",
        MinExpandX: 24,
        ExpandWidthScale: 0.14,
        MinExpandY: 10,
        ExpandHeightScale: 0.60,
        IncludeBrightTextUnion: true,
        InitialCloseKernelWidth: 7,
        InitialCloseKernelHeight: 3,
        DilateKernelWidth: 5,
        DilateKernelHeight: 3,
        AdaptiveHorizontalCloseDivisor: 6,
        AdaptiveHorizontalCloseMaxWidth: 61,
        FallbackConfidenceCap: 0.30,
        BrightThreshold: 138,
        LowSaturationThreshold: 118,
        TopHatThreshold: 10,
        StrokeThreshold: 18,
        CandidateIntensityThreshold: 150,
        MinComponentFillRatio: 0.07,
        MaxComponentFillRatio: 0.92,
        MinimumSolidBlockFillRatio: 0.70,
        LargeSolidBlockWidthRatio: 0.40,
        LargeSolidBlockHeightRatio: 0.56,
        LongEdgeAspectRatio: 7.0,
        LongEdgeFillRatio: 0.52);

    public static BottomTextWatermarkDetectorOptions Conservative { get; } = new(
        PresetName: "Conservative",
        MinExpandX: 14,
        ExpandWidthScale: 0.08,
        MinExpandY: 6,
        ExpandHeightScale: 0.34,
        IncludeBrightTextUnion: false,
        InitialCloseKernelWidth: 5,
        InitialCloseKernelHeight: 3,
        DilateKernelWidth: 3,
        DilateKernelHeight: 3,
        AdaptiveHorizontalCloseDivisor: 8,
        AdaptiveHorizontalCloseMaxWidth: 41,
        FallbackConfidenceCap: 0.20,
        BrightThreshold: 150,
        LowSaturationThreshold: 108,
        TopHatThreshold: 11,
        StrokeThreshold: 21,
        CandidateIntensityThreshold: 162,
        MinComponentFillRatio: 0.09,
        MaxComponentFillRatio: 0.88,
        MinimumSolidBlockFillRatio: 0.66,
        LargeSolidBlockWidthRatio: 0.36,
        LargeSolidBlockHeightRatio: 0.52,
        LongEdgeAspectRatio: 8.0,
        LongEdgeFillRatio: 0.48);

    public static BottomTextWatermarkDetectorOptions PrecisionBoost { get; } = new(
        PresetName: "PrecisionBoost",
        MinExpandX: 16,
        ExpandWidthScale: 0.08,
        MinExpandY: 6,
        ExpandHeightScale: 0.28,
        IncludeBrightTextUnion: false,
        InitialCloseKernelWidth: 5,
        InitialCloseKernelHeight: 3,
        DilateKernelWidth: 3,
        DilateKernelHeight: 3,
        AdaptiveHorizontalCloseDivisor: 9,
        AdaptiveHorizontalCloseMaxWidth: 35,
        FallbackConfidenceCap: 0.16,
        BrightThreshold: 154,
        LowSaturationThreshold: 104,
        TopHatThreshold: 12,
        StrokeThreshold: 23,
        CandidateIntensityThreshold: 166,
        MinComponentFillRatio: 0.10,
        MaxComponentFillRatio: 0.84,
        MinimumSolidBlockFillRatio: 0.62,
        LargeSolidBlockWidthRatio: 0.34,
        LargeSolidBlockHeightRatio: 0.48,
        LongEdgeAspectRatio: 8.8,
        LongEdgeFillRatio: 0.44);

    /// <summary>
    /// 桌面端增强预设——介于 Balanced 和 PrecisionBoost 之间。
    /// - 更高的亮度/梯度阈值，减少非文字区域的假阳性
    /// - 更小的 expand 系数，mask 紧贴水印轮廓
    /// - 更保守的 fallback 置信度上限
    /// </summary>
    public static BottomTextWatermarkDetectorOptions DesktopEnhanced { get; } = new(
        PresetName: "DesktopEnhanced",
        MinExpandX: 14,
        ExpandWidthScale: 0.06,
        MinExpandY: 6,
        ExpandHeightScale: 0.25,
        IncludeBrightTextUnion: false,
        InitialCloseKernelWidth: 5,
        InitialCloseKernelHeight: 3,
        DilateKernelWidth: 3,
        DilateKernelHeight: 3,
        AdaptiveHorizontalCloseDivisor: 8,
        AdaptiveHorizontalCloseMaxWidth: 41,
        FallbackConfidenceCap: 0.20,
        BrightThreshold: 148,
        LowSaturationThreshold: 110,
        TopHatThreshold: 12,
        StrokeThreshold: 22,
        CandidateIntensityThreshold: 160,
        MinComponentFillRatio: 0.09,
        MaxComponentFillRatio: 0.88,
        MinimumSolidBlockFillRatio: 0.66,
        LargeSolidBlockWidthRatio: 0.36,
        LargeSolidBlockHeightRatio: 0.52,
        LongEdgeAspectRatio: 8.0,
        LongEdgeFillRatio: 0.48);

    public static BottomTextWatermarkDetectorOptions Default { get; } = Balanced;
}
